### ISSUE TITLE
Should we still point to the 1.4.8 branch of https://github.com/hyperledger/fabric repo?

### ISSUE THREAD

**Issue by dasiths** [krypc-code/Hyperledger-Fabric-on-Azure-Kubernetes-Cluster#1]
https://github.com/krypc-code/Hyperledger-Fabric-on-Azure-Kubernetes-Cluster/blob/d2e6082abc68de5ee5476c3581fa8e402d0387c2/scripts/generateArtifacts.sh#L9

In the `generateArtefacts.sh` we still use 1.4.8 version.

```
docker build . -f ${dockerfileLocation} -t $1 \
    --build-arg GO_VERSION=1.13.12 \
    --build-arg ALPINE_VERSION=3.12 \
    --build-arg FABRIC_VERSION=1.4.8 \
    --build-arg FABRIC_CA_VERSION=1.4.8
popd
``` 
It then gets used in the `fabricTools.dockerfile`
```
RUN mkdir -p $GOPATH/src/github.com/hyperledger \
	&& git clone https://github.com/hyperledger/fabric.git --branch v${FABRIC_VERSION} \
		$GOPATH/src/github.com/hyperledger/fabric
```

I tried pointing to a newer version (2.2 / 2.3) but then the `Make` commands fail further along the docker build phase in `make .build/sampleconfig.tar.bz2 \` as that build target is no longer available in the new versions.

Are we ok to keep using 1.4.8 version of the repo?

**Comment by shivraj001** [comment]
It is been fixed in new commit with 2.2 fabric version
